name: build
on: [ push ]
jobs:
  Windows-Build:
    runs-on: windows-latest
    env:
      VS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
    steps:
      - name: Generate projects
        shell: cmd
        run: |
          cd ${{github.workspace}}\test
          ..\vendor\premake5.exe vs2019
      - name: Build Projects
        shell: cmd
        run: |
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          msbuild ..\scripts\test-workspace.sln
