name: build
on: [ push ]
jobs:
  windows-build:
    runs-on: windows-2019
    env:
      VS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v2
      - name: pull curl
        run: |
          git clone https://github.com/curl/curl ${{github.workspace}}/test/curl
      - name: generate projects
        shell: cmd
        run: |
          "${{github.workspace}}\vendor\premake5.exe" vs2019 --file="${{github.workspace}}\test\premake5.lua"
      - name: build projects
        shell: cmd
        run: |
          "%MSBUILD_PATH%\MSBuild.exe" "${{github.workspace}}\test\test-workspace.sln"
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull curl
        run: |
          git clone https://github.com/curl/curl ${{github.workspace}}/test/curl
      - name: generate projects
        run: |
          chmod +x ${{github.workspace}}/vendor/premake5
          ${{github.workspace}}/vendor/premake5 gmake --file=${{github.workspace}}/test/premake5.lua
      - name: install nasm
        run: |
          sudo apt-get install nasm
      - name: build projects
        run: |
          make -C ${{github.workspace}}/test